# Generated by Django 6.0.1 on 2026-01-12 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dentist", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dentist",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="workinghours",
            name="dentist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dentist.dentist"
            ),
        ),
    ]
